/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portlet.timesheet.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TimesheetTask service. Represents a row in the &quot;TS_TimesheetTask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.portlet.timesheet.model.impl.TimesheetTaskModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.portlet.timesheet.model.impl.TimesheetTaskImpl}.
 * </p>
 *
 * @author Mate Thurzo
 * @see TimesheetTask
 * @see com.liferay.portlet.timesheet.model.impl.TimesheetTaskImpl
 * @see com.liferay.portlet.timesheet.model.impl.TimesheetTaskModelImpl
 * @generated
 */
public interface TimesheetTaskModel extends BaseModel<TimesheetTask> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a timesheet task model instance should use the {@link TimesheetTask} interface instead.
	 */

	/**
	 * Returns the primary key of this timesheet task.
	 *
	 * @return the primary key of this timesheet task
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this timesheet task.
	 *
	 * @param primaryKey the primary key of this timesheet task
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the task ID of this timesheet task.
	 *
	 * @return the task ID of this timesheet task
	 */
	public long getTaskId();

	/**
	 * Sets the task ID of this timesheet task.
	 *
	 * @param taskId the task ID of this timesheet task
	 */
	public void setTaskId(long taskId);

	/**
	 * Returns the user ID of this timesheet task.
	 *
	 * @return the user ID of this timesheet task
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this timesheet task.
	 *
	 * @param userId the user ID of this timesheet task
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this timesheet task.
	 *
	 * @return the user uuid of this timesheet task
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this timesheet task.
	 *
	 * @param userUuid the user uuid of this timesheet task
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this timesheet task.
	 *
	 * @return the user name of this timesheet task
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this timesheet task.
	 *
	 * @param userName the user name of this timesheet task
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this timesheet task.
	 *
	 * @return the create date of this timesheet task
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this timesheet task.
	 *
	 * @param createDate the create date of this timesheet task
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this timesheet task.
	 *
	 * @return the modified date of this timesheet task
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this timesheet task.
	 *
	 * @param modifiedDate the modified date of this timesheet task
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the asset category ID of this timesheet task.
	 *
	 * @return the asset category ID of this timesheet task
	 */
	public long getAssetCategoryId();

	/**
	 * Sets the asset category ID of this timesheet task.
	 *
	 * @param assetCategoryId the asset category ID of this timesheet task
	 */
	public void setAssetCategoryId(long assetCategoryId);

	/**
	 * Returns the asset tag ID of this timesheet task.
	 *
	 * @return the asset tag ID of this timesheet task
	 */
	public long getAssetTagId();

	/**
	 * Sets the asset tag ID of this timesheet task.
	 *
	 * @param assetTagId the asset tag ID of this timesheet task
	 */
	public void setAssetTagId(long assetTagId);

	/**
	 * Returns the name of this timesheet task.
	 *
	 * @return the name of this timesheet task
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this timesheet task.
	 *
	 * @param name the name of this timesheet task
	 */
	public void setName(String name);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TimesheetTask timesheetTask);

	public int hashCode();

	public CacheModel<TimesheetTask> toCacheModel();

	public TimesheetTask toEscapedModel();

	public String toString();

	public String toXmlString();
}